[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Add this entire block
[dev]
  port = 8888 # Sets the port for the Netlify proxy server
  targetPort = 5173 # The port your Vite app is running on

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200