[build]
  command = "npm install && npm run build --workspace=frontend"
  publish = "frontend/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200