[build]
  command = "npm install && npm run build"
  publish = "dist"

[dev]
  command = "npm run dev:vite"
  port = 8888
  targetPort = 5173

# This redirect is for client-side routing, it should stay
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200